### ISSUE TITLE
Option to view admin notices should open in a new screen

### ISSUE THREAD

**Issue by foliovision** [foliovision/businesspress#16]
When I'm on the general preferences screen (for instance https://uncoy.com/site/wp-admin/index.php?page=businesspress-notices) I'm offered:

> Hide Admin Notices | Moves them all to a new screen in Dashboard -> Notices. There are 5 new notices, see them all here.

When I click that link I'm taken directly to the updates screen. I think it would be much better to open the updates screen in a new tab/window as I may very well have changed my preferences within BusinessPress when I click that link and I'd lose those changes.

Thanks.

**Comment by fvmartin** [comment]
Thank you for the bug report, I put in the fix into the current release.
